import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const pluginRoot = resolve(process.cwd(), "studio-plugin");

function readPluginFile(path: string): string {
  return readFileSync(resolve(pluginRoot, path), "utf8");
}

describe("STUDIO-1d canonical Roblox plugin contract", () => {
  it("wires one connector, lifecycle manager, loader, and sync manager", () => {
    const entry = readPluginFile("plugin.lua");

    expect(entry).toContain(
      "ConnectionManager.new(studioConnector, events, errorReporter)",
    );
    expect(entry).toContain(
      "SyncManager.new(studioConnector, artifactLoader, events, errorReporter)",
    );
    expect(
      entry.indexOf("local errorReporter = ErrorReporter.new()"),
    ).toBeGreaterThan(-1);
    expect(
      entry.indexOf("local artifactLoader = ArtifactLoader.new(errorReporter)"),
    ).toBeGreaterThan(
      entry.indexOf("local errorReporter = ErrorReporter.new()"),
    );
    expect(entry).not.toContain("RuntimeValidator.new()");
  });

  it("uses the existing REST command queue and acknowledgement lifecycle", () => {
    const connector = readPluginFile("src/services/StudioConnector.lua");
    const sync = readPluginFile("src/services/SyncManager.lua");

    expect(connector).toContain("script.Parent.Parent.core.Config");
    expect(connector).toContain("/api/studio/commands?clientId=");
    expect(connector).toContain("/acknowledge");
    expect(connector).toContain("/result");
    expect(connector).toContain("function StudioConnector:connect(projectId)");

    expect(sync).toContain('command.type == "EXPORT_PROJECT"');
    expect(sync).toContain("self._connector:getCommands()");
    expect(sync).toContain("self._connector:acknowledgeCommand(command.id)");
    expect(sync).toContain("self._connector:reportCommand(command.id");
    expect(sync).not.toContain('sendMessage("GET_PROJECT"');
    expect(sync).not.toContain('sendMessage("GET_ARTIFACTS"');

    const acknowledgeIndex = sync.indexOf(
      "self._connector:acknowledgeCommand(command.id)",
    );
    const completedResultIndex = sync.indexOf(
      'status = "completed"',
      acknowledgeIndex,
    );
    expect(acknowledgeIndex).toBeGreaterThan(-1);
    expect(completedResultIndex).toBeGreaterThan(acknowledgeIndex);
    expect(sync.lastIndexOf("return SyncManager")).toBeGreaterThan(
      sync.indexOf("function SyncManager:destroy()"),
    );
  });

  it("materializes durable Lua outputs and metadata without placeholder scripts", () => {
    const loader = readPluginFile("src/utils/ArtifactLoader.lua");

    expect(loader).toContain("content.scripts");
    expect(loader).toContain('fileName:match("%.server%.lua$")');
    expect(loader).toContain('fileName:match("%.client%.lua$")');
    expect(loader).toContain('Instance.new("StringValue")');
    expect(loader).toContain('root.Name = "AIStudioArtifacts"');
    expect(loader).toContain("instance.Source = source");
    expect(loader).not.toContain('content.script or "-- Generated"');
    expect(loader).not.toContain("-- Generated by AI Studio");
  });

  it("reports exactly one receipt for every queued pipeline artifact", () => {
    const sync = readPluginFile("src/services/SyncManager.lua");

    expect(sync).toContain("expectedById[artifactRef.id] = artifactRef");
    expect(sync).toContain("artifactId = artifact.id");
    expect(sync).toContain("hash = expected.hash");
    expect(sync).toContain("instancePath = loaded.instancePath");
    expect(sync).toContain("#receipts ~= #payload.snapshot.artifacts");
    expect(sync).toContain("result.data.verified ~= true");
  });

  it("requires the canonical backend project id before connecting", () => {
    const connector = readPluginFile("src/services/StudioConnector.lua");
    const panel = readPluginFile("src/ui/CommandPanel.lua");

    expect(connector).toContain("local resolvedProjectId = projectId");
    expect(connector).toContain("projectId = resolvedProjectId");
    expect(panel).toContain('GetSetting("AIStudioProjectId")');
    expect(panel).toContain('SetSetting("AIStudioProjectId", projectId)');
    expect(panel).toContain('self:_textBox(frame, "Project ID"');
    expect(panel).toContain('self:_updateStatus("Project ID required"');
    expect(panel).toContain('GetSetting("AIStudioApiKey")');
    expect(panel).toContain('SetSetting("AIStudioApiKey", apiKey)');
    expect(connector).toContain('headers["X-API-Key"] = self._apiKey');
    expect(connector).not.toContain("Config.API_KEY");
  });

  it("keeps the active plugin modules syntactically coherent", () => {
    const connection = readPluginFile("src/services/ConnectionManager.lua");
    const sync = readPluginFile("src/services/SyncManager.lua");
    const panel = readPluginFile("src/ui/CommandPanel.lua");
    const config = readPluginFile("src/core/Config.lua");

    expect(connection).toContain("script.Parent.Parent.core.Config");
    expect(connection).toContain(
      "function ConnectionManager.new(connector, events, errorReporter)",
    );
    expect(connection).toContain("self._connector:connect(self._projectId)");
    expect(sync).toContain("script.Parent.Parent.core.Config");
    expect(panel).toContain("script.Parent.Parent.core.Config");
    expect(panel).not.toContain("end:updaeSt");
    expect(panel).not.toContain("self._statusLabel");
    expect(panel).toContain('self:_updateStatus("Verified"');
    expect(config).toContain('Config.PLUGIN_VERSION = "1.11.0"');
    expect(config).toContain("Config.COMMAND_POLL_INTERVAL = 2");
  });
});
