/**
 * ModuleBuilder.ts — Converts ModuleDefinitions into ModuleScript artifacts.
 */

import type { ModuleDefinition } from "../GenerationModel";
import type { ProjectNode } from "../model/RobloxProjectModel";

export interface BuiltModule {
  node: ProjectNode;
  path: string;
  content: string;
  sizeBytes: number;
}

export class ModuleBuilder {
  /**
   * Build a ModuleScript node from a ModuleDefinition.
   */
  build(mod: ModuleDefinition): BuiltModule {
    const content = this.generateModuleContent(mod);
    return {
      node: { name: mod.name, type: "ModuleScript", path: mod.path, content },
      path: mod.path,
      content,
      sizeBytes: content.length * 2,
    };
  }

  buildAll(modules: ModuleDefinition[]): BuiltModule[] {
    return modules.map((m) => this.build(m));
  }

  private generateModuleContent(mod: ModuleDefinition): string {
    const lines = [
      `-- Module: ${mod.name}`,
      `-- Auto-generated by Roblox AI Studio DevKit`,
      ``,
      `local ${mod.name} = {}`,
      ``,
    ];

    for (const exp of mod.exports) {
      lines.push(`function ${mod.name}.${exp}()`);
      lines.push(`    -- TODO: Implement ${exp}`);
      lines.push(`end`);
      lines.push(``);
    }

    lines.push(`return ${mod.name}`);
    return lines.join("\n");
  }
}
