import { BaseAgent, type AgentConfig } from "../core/BaseAgent";
import type { AgentInput } from "../../types";

export class DocumentationAgent extends BaseAgent {
  public readonly name = "Documentation";
  public readonly description =
    "Generates README and API documentation for the game project";

  public readonly inputSchema: Record<string, unknown> = {
    type: "object",
    properties: {
      architecture: { type: "object" },
      lua_generator: { type: "object" },
      blueprint: { type: "object" },
    },
  };

  public readonly outputSchema: Record<string, unknown> = {
    type: "object",
    properties: { documentation: { type: "object" } },
    required: ["documentation"],
  };

  constructor(config?: Partial<AgentConfig>) {
    super(config);
  }

  protected async process(input: AgentInput): Promise<Record<string, unknown>> {
    const bp = input.blueprint as Record<string, unknown> | undefined;
    const name = String(bp?.name ?? "Unnamed Game");

    const fallback: Record<string, unknown> = {
      documentation: {
        readme: `# ${name}\n\nA Roblox game generated by the AI DevKit.\n\n## Setup\n1. Open in Roblox Studio\n2. Configure DataStore keys\n3. Publish\n`,
        api: {
          remoteEvents: ["Player.Join", "Game.StateChange", "UI.Update"],
          serverModules: [],
          clientModules: [],
        },
      },
    };

    if (!this.llm) return fallback;

    const prompt =
      "You are a Roblox technical writer. Generate project documentation. " +
      'Respond with: { "documentation": { "readme": string, "api": { "remoteEvents": string[], ' +
      '"serverModules": string[], "clientModules": string[] } } }\n\n' +
      `Game: ${name}\n\nReturn only valid JSON.`;

    return this.generateWithRetry(prompt, ["documentation"], fallback, {
      temperature: 0.4,
      maxTokens: 1000,
    });
  }
}
