import type {
  AgentInput,
  AgentOutput,
  AgentStatus,
  AgentType,
} from "../../types";
import { BaseAgent, type AgentConfig } from "../core/BaseAgent";
import { LLMOutputParser } from "../../ai/outputParser";

/**
 * OrchestratorAgent
 *
 * Dual-mode final stage of the generation pipeline:
 *
 * Mode A — Final aggregation (default, called by AIPipelineIntegrator as last stage):
 *   Receives blueprint + all accumulated prior-step outputs.
 *   When LLM is available: synthesises a coherent world definition and
 *   gameplay system summary via a structured prompt.
 *   When no LLM: derives the summary deterministically from accumulated inputs.
 *   Output is consumed by aggregateToGameGenerationResult under the `orchestrator` key.
 *
 * Mode B — Coordination (when input.pipeline is an AgentType[]):
 *   Delegates to injected AgentRegistry. Used for standalone sub-pipeline runs.
 */
export class OrchestratorAgent extends BaseAgent {
  public readonly name = "Orchestrator";
  public readonly description =
    "Synthesises all agent outputs into a final coherent game artifact summary.";

  public readonly inputSchema: Record<string, unknown> = {
    type: "object",
    properties: {
      blueprint: { type: "object" },
      pipeline: { type: "array", items: { type: "string" } },
      input: { type: "object" },
    },
  };

  public readonly outputSchema: Record<string, unknown> = {
    type: "object",
    properties: {
      name: { type: "string" },
      description: { type: "string" },
      world: { type: "object" },
      systems: { type: "array" },
      status: { type: "string" },
    },
    required: ["status"],
  };

  private registry?: {
    executeAgent(
      type: string,
      input: Record<string, unknown>,
    ): Promise<Record<string, unknown>>;
  };

  constructor(config?: Partial<AgentConfig>) {
    super(config);
  }

  setRegistry(registry: {
    executeAgent(
      type: string,
      input: Record<string, unknown>,
    ): Promise<Record<string, unknown>>;
  }): void {
    this.registry = registry;
  }

  protected async process(input: AgentInput): Promise<AgentOutput> {
    if (Array.isArray(input.pipeline)) {
      return this.runCoordination(input);
    }
    return this.runFinalAggregation(input);
  }

  // ─── Mode A: Final aggregation ──────────────────────────────────────────────

  private async runFinalAggregation(input: AgentInput): Promise<AgentOutput> {
    const blueprint = input.blueprint as Record<string, unknown> | undefined;
    const gameplay = input.gameplay as Record<string, unknown> | undefined;
    const arch =
      (input.roblox_architect as Record<string, unknown> | undefined) ??
      (input.architecture as Record<string, unknown> | undefined);

    const name =
      typeof (blueprint as any)?.name === "string"
        ? (blueprint as any).name
        : "Generated Game";

    const description =
      typeof (blueprint as any)?.description === "string"
        ? (blueprint as any).description
        : "A Roblox game generated by the AI pipeline.";

    // Derive systems list from game_designer output (always available as fallback)
    const systems: Array<Record<string, unknown>> = [];
    const mechanicsArr = (gameplay as any)?.mechanics;
    if (Array.isArray(mechanicsArr)) {
      for (const m of mechanicsArr) {
        if (m && typeof m === "object") {
          systems.push({
            name: String((m as any).name ?? "Mechanic"),
            description: String((m as any).description ?? ""),
          });
        }
      }
    }

    const fallback: AgentOutput = {
      status: "completed",
      name,
      description,
      world: {
        name,
        description,
        places: [],
        models: [],
        systemsHooks:
          typeof (arch as any)?.services === "object"
            ? (arch as any).services
            : {},
      },
      systems,
    };

    if (!this.llm) return fallback;

    // Summarise what was built for the synthesis prompt
    const systemsBuilt =
      systems.map((s) => String(s.name)).join(", ") || "none";
    const luaOutput = input.lua_generator as
      | Record<string, unknown>
      | undefined;
    const serverScripts = Array.isArray((luaOutput as any)?.server)
      ? (luaOutput as any).server
          .map((s: any) => String(s?.name ?? s))
          .join(", ")
      : "none";

    // Use PromptTemplateRegistry as single source of truth for prompt content.
    const registryPrompt = this.buildPrompt({
      name,
      description,
      systems_built: systemsBuilt,
      modules_built: serverScripts,
    });

    const inlinePrompt =
      "You are the final synthesis stage of a Roblox game generation pipeline. " +
      "Synthesise all prior agent outputs into a coherent world definition and system summary. " +
      "Respond with a single JSON object:\n" +
      '{ "name": string, "description": string, ' +
      '"world": { "name": string, "description": string, "places": Array<{name,description}>, ' +
      '"models": Array<{name,purpose}>, "systemsHooks": object }, ' +
      '"systems": Array<{name,description,config?: object}>, ' +
      '"status": "completed" }\n\n' +
      `Game Name: ${name}\nGame Description: ${description}\n` +
      `Gameplay Systems Built: ${systemsBuilt}\nServer Scripts: ${serverScripts}\n\n` +
      "Produce a coherent, complete world definition. Return only valid JSON.";

    const prompt = registryPrompt ?? inlinePrompt;

    const raw = await this.llm.generate(prompt, {
      temperature: 0.5,
      maxTokens: 2000,
    });

    const parsed = LLMOutputParser.parseAndValidate(
      raw,
      ["name", "world", "systems", "status"],
      fallback as Record<string, unknown>,
      this.name,
    );

    // Ensure status is always present
    if (!parsed.status) parsed.status = "completed";

    return parsed;
  }

  // ─── Mode B: Coordination ───────────────────────────────────────────────────

  private async runCoordination(input: AgentInput): Promise<AgentOutput> {
    const pipeline = input.pipeline as AgentType[];
    const userInput = (input.input as AgentInput | undefined) ?? {};
    const pipelineRunId = `run_${Date.now()}`;

    const steps: Array<{
      agent: string;
      status: AgentStatus;
      startedAt: string;
      finishedAt?: string;
    }> = [];

    let currentInput: Record<string, unknown> = { ...userInput };

    for (const agentType of pipeline) {
      const startedAt = new Date();

      if (!this.registry) {
        steps.push({
          agent: agentType,
          status: "failed",
          startedAt: startedAt.toISOString(),
          finishedAt: new Date().toISOString(),
        });
        break;
      }

      try {
        const output = await this.registry.executeAgent(
          agentType,
          currentInput,
        );
        const failed = (output as any)._failed === true;
        steps.push({
          agent: agentType,
          status: failed ? "failed" : "completed",
          startedAt: startedAt.toISOString(),
          finishedAt: new Date().toISOString(),
        });
        if (failed) break;
        currentInput = { ...currentInput, ...output };
      } catch {
        steps.push({
          agent: agentType,
          status: "failed",
          startedAt: startedAt.toISOString(),
          finishedAt: new Date().toISOString(),
        });
        break;
      }
    }

    const status = steps.some((s) => s.status === "failed")
      ? "failed"
      : "completed";
    const completedSteps = steps.filter((s) => s.status === "completed");

    return {
      pipelineRunId,
      status,
      steps,
      finalOutput: completedSteps.length > 0 ? currentInput : {},
    };
  }
}
