--[[
  ArtifactLoader — Creates Roblox Instances from artifact data.
]]

local ServerScriptService = game:GetService("ServerScriptService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local StarterGui = game:GetService("StarterGui")
local StarterPlayer = game:GetService("StarterPlayer")

local ArtifactLoader = {}
ArtifactLoader.__index = ArtifactLoader

function ArtifactLoader.new(errorReporter)
    local self = setmetatable({}, ArtifactLoader)
    self._errors = errorReporter
    self._loaded = {}
    return self
end

function ArtifactLoader:load(artifact)
    local success, err = pcall(function()
        self:_createInstance(artifact)
    end)
    if not success then
        self._errors:report("Failed to load " .. (artifact.name or "unknown") .. ": " .. tostring(err))
    end
end

function ArtifactLoader:_createInstance(artifact)
    local parent = self:_resolveParent(artifact.stage or artifact.type or "")
    local name = artifact.name or "GeneratedScript"
    name = name:gsub("%.lua$", "")

    -- Remove existing if present
    local existing = parent:FindFirstChild(name)
    if existing then existing:Destroy() end

    local scriptType = self:_resolveScriptType(artifact.type or "ModuleScript")
    local inst = Instance.new(scriptType)
    inst.Name = name

    if inst:IsA("LuaSourceContainer") then
        local content = artifact.content
        if typeof(content) == "table" then
            content = tostring(content.content or content.script or "-- Generated")
        end
        inst.Source = tostring(content or "-- Generated by AI Studio")
    end

    inst.Parent = parent
    table.insert(self._loaded, { name = name, type = scriptType, parent = parent:GetFullName() })
end

function ArtifactLoader:_resolveParent(stageOrType)
    local lower = string.lower(stageOrType)
    if lower:find("server") or lower:find("game_manager") or lower:find("data") then
        return ServerScriptService
    elseif lower:find("ui") or lower:find("gui") or lower:find("starter_gui") then
        return StarterGui
    elseif lower:find("local") or lower:find("player") or lower:find("starter_player") then
        return StarterPlayer:FindFirstChild("StarterPlayerScripts") or StarterPlayer
    end
    return ReplicatedStorage
end

function ArtifactLoader:_resolveScriptType(artifactType)
    if artifactType == "ServerScript" or artifactType == "Script" then return "Script" end
    if artifactType == "LocalScript" then return "LocalScript" end
    return "ModuleScript"
end

function ArtifactLoader:getLoaded()
    return self._loaded
end

function ArtifactLoader:clear()
    self._loaded = {}
end

return ArtifactLoader
