/**
 * BaseLuaTemplate.ts — Abstract Lua template base.
 */

export interface TemplateContext {
  name: string;
  metadata: Record<string, unknown>;
  [key: string]: unknown;
}

export abstract class BaseLuaTemplate {
  abstract readonly templateId: string;

  abstract render(context: TemplateContext): string;

  protected header(title: string, generator: string): string {
    return `-- ${title}\n-- Generated by: ${generator}\n-- Roblox AI Studio DevKit\n`;
  }

  protected luaString(value: string): string {
    return `"${value.replace(/"/g, '\\"')}"`;
  }
  protected luaNumber(value: number): string {
    return String(value);
  }
  protected luaBool(value: boolean): string {
    return String(value);
  }

  protected luaTable(obj: Record<string, unknown>, indent = 1): string {
    const pad = "    ".repeat(indent);
    const entries = Object.entries(obj).map(
      ([k, v]) => `${pad}${k} = ${this.luaValue(v, indent)}`,
    );
    return `{\n${entries.join(",\n")}\n${"    ".repeat(indent - 1)}}`;
  }

  protected luaValue(value: unknown, indent = 1): string {
    if (value === null || value === undefined) return "nil";
    if (typeof value === "string") return this.luaString(value);
    if (typeof value === "number") return this.luaNumber(value);
    if (typeof value === "boolean") return this.luaBool(value);
    if (Array.isArray(value))
      return `{${value.map((v) => this.luaValue(v, indent)).join(", ")}}`;
    if (typeof value === "object")
      return this.luaTable(value as Record<string, unknown>, indent + 1);
    return "nil";
  }
}
