--[[
  SyncManager — Handles project synchronization between backend and Roblox Studio.
  Currently supports syncing Lua scripts into ServerScriptService.
]]

local ServerScriptService = game:GetService("ServerScriptService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local SyncManager = {}
SyncManager.__index = SyncManager

function SyncManager.new(apiClient, events)
    local self = setmetatable({}, SyncManager)
    self._api = apiClient
    self._events = events
    self._lastSyncTime = nil
    self._syncedArtifacts = {}
    return self
end

function SyncManager:getLastSyncTime()
    return self._lastSyncTime
end

function SyncManager:getSyncedCount()
    return #self._syncedArtifacts
end

function SyncManager:syncProject(projectId)
    self._events:fire("PROJECT_SYNC_STARTED", { projectId = projectId })

    -- Get project snapshot
    local snapshot = self._api:syncProject(projectId)
    if not snapshot or not snapshot.success then
        self._events:fire("PROJECT_SYNC_FAILED", {
            error = snapshot and snapshot.error or "Failed to fetch project",
        })
        return false
    end

    local data = snapshot.data
    if not data or not data.artifacts then
        self._events:fire("PROJECT_SYNC_COMPLETED", {
            projectId = projectId,
            artifactCount = 0,
        })
        self._lastSyncTime = os.time()
        return true
    end

    -- Find Lua artifacts and sync them
    local luaArtifacts = {}
    for _, artifact in ipairs(data.artifacts) do
        if artifact.type == "lua" then
            table.insert(luaArtifacts, artifact.id)
        end
    end

    if #luaArtifacts > 0 then
        local transferResult = self._api:syncArtifacts(luaArtifacts)
        if transferResult and transferResult.success and transferResult.data then
            for _, artifact in ipairs(transferResult.data.artifacts or {}) do
                self:_applyScript(artifact)
                table.insert(self._syncedArtifacts, artifact.id)
            end
        end
    end

    self._lastSyncTime = os.time()
    self._events:fire("PROJECT_SYNC_COMPLETED", {
        projectId = projectId,
        artifactCount = #luaArtifacts,
    })

    return true
end

function SyncManager:_applyScript(artifact)
    local scriptName = artifact.name or "GeneratedScript"
    scriptName = scriptName:gsub("%.lua$", "")

    -- Determine target location based on stage
    local parent = ServerScriptService
    if artifact.stage == "UI_GENERATION" then
        parent = ReplicatedStorage
    end

    -- Create or update the script
    local existing = parent:FindFirstChild(scriptName)
    if existing and existing:IsA("ModuleScript") then
        existing.Source = tostring(artifact.content or "-- Empty")
        self._events:fire("SCRIPT_UPDATED", { name = scriptName })
    else
        if existing then existing:Destroy() end
        local newScript = Instance.new("ModuleScript")
        newScript.Name = scriptName
        newScript.Source = tostring(artifact.content or "-- Generated by AI Studio")
        newScript.Parent = parent
        self._events:fire("SCRIPT_CREATED", { name = scriptName })
    end
end

function SyncManager:destroy()
    self._syncedArtifacts = {}
end

return SyncManager
