/**
 * ScriptGenerator.ts — Generates Lua scripts from GenerationModel.
 */

import {
  BaseGenerator,
  type GeneratorInput,
  type GeneratorOutput,
  type GeneratorMetadata,
} from "../BaseGenerator";
import type { ScriptDefinition } from "../GenerationModel";

export class ScriptGenerator extends BaseGenerator {
  readonly metadata: GeneratorMetadata = {
    id: "script-generator",
    name: "Script Generator",
    version: "1.0.0",
    dependencies: ["service-generator"],
    produces: ["scripts"],
  };

  async generate(input: GeneratorInput): Promise<GeneratorOutput> {
    const start = Date.now();
    const { model, blueprint } = input;
    const modifications: string[] = [];

    const mechanics =
      (blueprint.mechanics as string[]) ?? model.game.mechanics ?? [];
    const gameType = (blueprint.game_type as string) ?? model.game.genre;

    // Generate server main script
    model.scripts.push(
      this.createScript(
        "MainGameLoop",
        "server",
        "ServerScriptService/MainGameLoop.lua",
        this.generateServerMain(model.game.title, gameType),
      ),
    );
    modifications.push("ServerScriptService/MainGameLoop.lua");

    // Generate client controller
    model.scripts.push(
      this.createScript(
        "ClientController",
        "client",
        "StarterPlayerScripts/ClientController.lua",
        this.generateClientController(model.game.title),
      ),
    );
    modifications.push("StarterPlayerScripts/ClientController.lua");

    // Generate mechanic scripts
    for (const mechanic of mechanics.slice(0, 5)) {
      const name = this.sanitizeName(mechanic);
      model.scripts.push(
        this.createScript(
          `${name}Handler`,
          "server",
          `ServerScriptService/${name}Handler.lua`,
          this.generateMechanicScript(mechanic),
        ),
      );
      modifications.push(`ServerScriptService/${name}Handler.lua`);
    }

    return {
      generatorId: this.metadata.id,
      success: true,
      modifications,
      durationMs: Date.now() - start,
    };
  }

  private createScript(
    name: string,
    scriptType: ScriptDefinition["scriptType"],
    path: string,
    content: string,
  ): ScriptDefinition {
    return {
      id: `script-${name.toLowerCase()}`,
      name,
      path,
      scriptType,
      content,
      dependencies: [],
      generatedBy: this.metadata.id,
    };
  }

  private generateServerMain(title: string, gameType: string): string {
    return [
      `-- ${title} - Server Main Loop`,
      `-- Game Type: ${gameType}`,
      `-- Auto-generated by Roblox AI Studio DevKit`,
      ``,
      `local Players = game:GetService("Players")`,
      `local ReplicatedStorage = game:GetService("ReplicatedStorage")`,
      ``,
      `local GameManager = {}`,
      `GameManager.__index = GameManager`,
      ``,
      `function GameManager.new()`,
      `    local self = setmetatable({}, GameManager)`,
      `    self.active = false`,
      `    self.players = {}`,
      `    return self`,
      `end`,
      ``,
      `function GameManager:Start()`,
      `    self.active = true`,
      `    print("[${title}] Game started")`,
      `end`,
      ``,
      `function GameManager:OnPlayerAdded(player)`,
      `    table.insert(self.players, player)`,
      `    print("[${title}] Player joined: " .. player.Name)`,
      `end`,
      ``,
      `local manager = GameManager.new()`,
      `Players.PlayerAdded:Connect(function(player) manager:OnPlayerAdded(player) end)`,
      `manager:Start()`,
    ].join("\n");
  }

  private generateClientController(title: string): string {
    return [
      `-- ${title} - Client Controller`,
      `-- Auto-generated by Roblox AI Studio DevKit`,
      ``,
      `local Players = game:GetService("Players")`,
      `local ReplicatedStorage = game:GetService("ReplicatedStorage")`,
      `local player = Players.LocalPlayer`,
      ``,
      `local ClientController = {}`,
      ``,
      `function ClientController:Init()`,
      `    print("[Client] Initialized for " .. player.Name)`,
      `end`,
      ``,
      `ClientController:Init()`,
    ].join("\n");
  }

  private generateMechanicScript(mechanic: string): string {
    const name = this.sanitizeName(mechanic);
    return [
      `-- ${mechanic} Handler`,
      `-- Auto-generated mechanic implementation`,
      ``,
      `local ${name}Handler = {}`,
      `${name}Handler.__index = ${name}Handler`,
      ``,
      `function ${name}Handler.new()`,
      `    local self = setmetatable({}, ${name}Handler)`,
      `    self.enabled = true`,
      `    return self`,
      `end`,
      ``,
      `function ${name}Handler:Execute(player, context)`,
      `    if not self.enabled then return end`,
      `    print("[${mechanic}] Executing for " .. player.Name)`,
      `end`,
      ``,
      `return ${name}Handler`,
    ].join("\n");
  }

  private sanitizeName(str: string): string {
    return (
      str.replace(/[^a-zA-Z0-9]/g, "").replace(/^[0-9]/, "_$&") || "Default"
    );
  }
}
